name: Send Email on Workflow Completion

on:
  workflow_completion: {} # Trigger on any workflow completion

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }} # Use GitHub secrets
          password: ${{ secrets.EMAIL_PASSWORD }} # Use GitHub secrets
          from: samanurumahitha@gmail.com
          to: samanurumahitha@gmail.com
          subject: Workflow ${{ github.workflow }} completed
          body: >
            Workflow ${{ github.workflow }} in ${{ github.repository }}
            completed with ${{ job.status }}
